### ISSUE TITLE
Command completion race condition

### ISSUE THREAD

**Issue by d4rken** [d4rken/RxShell#4]
Seeing a rare racecondition likely related to `Observable.zip` in https://github.com/d4rken/RxShell/blob/master/core/src/main/java/eu/darken/rxshell/cmd/CmdProcessor.java#L111

```
1513428431737 V/RXS:RxCmdShell: open()
1513428431738 V/RXS:RxShell: open()
1513428431738 V/RXS:RxProcess: open()
1513428431740 V/RXS:RxProcess: processCreator:onNext(Process[pid=5851, hasExited=false])
1513428431740 D/RXS:RxProcess: open():doOnSuccess RxProcess.Session(process=Process[pid=5851, hasExited=false])
1513428431740 V/RXS:RxProcess:Session: input()
1513428431740 V/RXS:RxProcess:Session: output()
1513428431740 V/RXS:RxProcess:Session: error()
1513428431740 V/RXS:RxShell:Session: errorLines()
1513428431740 V/RXS:RxProcess:Session: destroy()
1513428431740 V/RXS:RxProcess:Session: waitFor()
1513428431740 V/RXS:RxShell:Session: waitFor()
1513428431740 V/RXS:RxShell: open():doOnSuccess RxShell.Session(processSession=RxProcess.Session(process=Process[pid=5851, hasExited=false]))
1513428431740 V/RXS:RxShell:Session: waitFor()
1513428431741 D/RXS:RxShell:Session: writeLine(line=V5B9D812A9C51=/data/user/0/eu.thedarken.sdm/files/toybox_sdm, flush=true)
1513428431741 V/RXS:CmdProcessor: attach(RxShell.Session(processSession=RxProcess.Session(process=Process[pid=5851, hasExited=false])))
1513428431741 V/RXS:RxShell:Session: waitFor()
1513428431741 V/RXS:RxShell:Session: waitFor()
1513428431741 V/RXS:RxShell:Session: cancel()
1513428431741 V/RXS:RxCmdShell: open():doOnSuccess eu.darken.rxshell.cmd.RxCmdShell$Session@9b97c1513428431741 V/RXS:RxCmdShell:Session: waitFor()
1513428431742 D/RXS:RxProcess:Session: Waiting for Process[pid=5851, hasExited=false] to exit.
1513428431742 D/RXS:CmdProcessor: Submitted: Cmd(timeout=0, commands=[$V5B9D812A9C51 test ! -e '/storage/emulated/0' || $V5B9D812A9C51 find -L '/storage/emulated/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user_de/0' || $V5B9D812A9C51 find -L '/data/user_de/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user/0' || $V5B9D812A9C51 find -L '/data/user/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N"])
1513428431742 D/RXS:CmdProcessor: Processing: Cmd(timeout=0, commands=[$V5B9D812A9C51 test ! -e '/storage/emulated/0' || $V5B9D812A9C51 find -L '/storage/emulated/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user_de/0' || $V5B9D812A9C51 find -L '/data/user_de/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user/0' || $V5B9D812A9C51 find -L '/data/user/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N"])
1513428431742 V/RXS:RxShell:Session: outputLines()
1513428431742 V/RXS:Harvester:Output: request(9223372036854775807)
1513428431742 V/RXS:RxShell:Session: errorLines()
1513428431742 V/RXS:Harvester:Error: request(9223372036854775807)
1513428431742 D/RXS:RxShell:Session: writeLine(line=$V5B9D812A9C51 test ! -e '/storage/emulated/0' || $V5B9D812A9C51 find -L '/storage/emulated/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", flush=false)
1513428431742 D/RXS:RxShell:Session: writeLine(line=$V5B9D812A9C51 test ! -e '/data/user_de/0' || $V5B9D812A9C51 find -L '/data/user_de/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", flush=false)
1513428431742 D/RXS:RxShell:Session: writeLine(line=$V5B9D812A9C51 test ! -e '/data/user/0' || $V5B9D812A9C51 find -L '/data/user/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", flush=false)
1513428431742 D/RXS:RxShell:Session: writeLine(line=echo fb6e4bdf-16ae-4f0d-b1b8-c3445f5d7ec1 $?, flush=false)
1513428431742 D/RXS:RxShell:Session: writeLine(line=echo fb6e4bdf-16ae-4f0d-b1b8-c3445f5d7ec1 >&2, flush=true)
1513428431775 V/RXS:Harvester:Error: Permission denied
1513428431775 D/RXS:Harvester:Error: Permission denied
1513428431776 V/RXS:RxShell: LineStream:error onComplete()
1513428431776 V/RXS:RxShell: LineStream:output onComplete()
1513428431776 V/RXS:Harvester:Error: onComplete()
1513428431776 V/RXS:Harvester:Output: onComplete()
1513428431776 V/RXS:Harvester:Error: onError(java.io.IOException: Upstream completed prematurely.)
1513428431776 V/RXS:Harvester:Output: onError(java.io.IOException: Upstream completed prematurely.)
1513428431776 V/RXS:CmdProcessor: errorLines():doOnEach: OnNextNotification[eu.darken.rxshell.cmd.Harvester$Crop@519a13a]
1513428431776 V/RXS:CmdProcessor: outputLine():doOnEach: OnNextNotification[eu.darken.rxshell.cmd.OutputHarvester$Crop@7e581eb]
1513428431776 V/RXS:RxProcess: processCreator:onComplete()
1513428431776 V/RXS:CmdProcessor: errorLines():doOnEach: OnCompleteNotification
1513428431776 V/RXS:Harvester:Error: cancel()
1513428431776 V/RXS:RxProcess: cancel()
1513428431777 D/RXS:RootKiller: kill(Process[pid=5851 ,hasExited=true, exitcode=1])
1513428431777 D/RXS:RootKiller: Process is no longer alive, skipping kill.
1513428431777 V/RXS:RxProcess: Process finished, clearing session
1513428431777 V/RXS:RxShell: LineStream:error onCancel()
1513428431777 D/RXS:RxProcess:Session: Exitcode: 1, Process: Process[pid=5851 ,hasExited=true, exitcode=1]
1513428431777 V/RXS:RxProcess:Session: waitFor():doOnSuccess 1513428431777 V/RXS:RxShell:Session: waitFor():doOnSuccess 1513428431777 V/RXS:CmdProcessor: Attached session ended!
1513428431777 V/RXS:CmdProcessor: Poison pill!
1513428431777 D/RXS:CmdProcessor: Post zip: OnNextNotification[QueueCmd(command=Cmd(timeout=0, commands=[$V5B9D812A9C51 test ! -e '/storage/emulated/0' || $V5B9D812A9C51 find -L '/storage/emulated/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user_de/0' || $V5B9D812A9C51 find -L '/data/user_de/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user/0' || $V5B9D812A9C51 find -L '/data/user/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N"]), exitCode=-3, output.size()=null, errors.size()=null)]
1513428431777 V/RXS:CmdProcessor: onNext(QueueCmd(command=Cmd(timeout=0, commands=[$V5B9D812A9C51 test ! -e '/storage/emulated/0' || $V5B9D812A9C51 find -L '/storage/emulated/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user_de/0' || $V5B9D812A9C51 find -L '/data/user_de/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user/0' || $V5B9D812A9C51 find -L '/data/user/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N"]), exitCode=-3, output.size()=null, errors.size()=null))
1513428431777 V/RXS:RxShell:Session: cancel()
1513428431777 I/RXS:CmdProcessor: Processed: Cmd.Result(cmd=Cmd(timeout=0, commands=[$V5B9D812A9C51 test ! -e '/storage/emulated/0' || $V5B9D812A9C51 find -L '/storage/emulated/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user_de/0' || $V5B9D812A9C51 find -L '/data/user_de/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N", $V5B9D812A9C51 test ! -e '/data/user/0' || $V5B9D812A9C51 find -L '/data/user/0' -mindepth 1 -print0 | $V5B9D812A9C51 xargs -0 -r -s 65536 $V5B9D812A9C51 stat -c "%a:%F:%d:%i:%u:%g:%s:%B:%b:%Y:%N"]), exitcode=-3, output.size()=null, errors.size()=null)
1513428431777 V/RXS:RxProcess:Session: destroy():doOnComplete
1513428431777 D/RXS:CmdProcessor: Post zip: OnCompleteNotification
1513428431777 V/RXS:RxShell:Session: cancel():doOnComplete
1513428431777 V/RXS:CmdProcessor: onComplete()
1513428431777 V/RXS:CmdProcessor: outputLine():doOnEach: OnCompleteNotification
1513428431777 V/RXS:Harvester:Output: cancel()
io.reactivex.exceptions.OnErrorNotImplementedException: Upstream completed prematurely.
	at io.reactivex.e.b.a$af.accept(Functions.java:1704)
	at io.reactivex.e.h.k.onError(LambdaSubscriber.java:79)
	at io.reactivex.i.b.onError(PublishProcessor.java:2325)
	at eu.darken.rxshell.cmd.Harvester$BaseSub.onError(Harvester.java:96)
	at eu.darken.rxshell.cmd.Harvester$BaseSub.onComplete(Harvester.java:102)
	at io.reactivex.e.j.k.a(HalfSerializer.java:91)
	at io.reactivex.e.h.s.onComplete(StrictSubscriber.java:109)
	at io.reactivex.e.e.b.co$a.onComplete(FlowableRefCount.java:82)
	at io.reactivex.e.e.b.cg$c.a(FlowablePublish.java:366)
	at io.reactivex.e.e.b.cg$c.c(FlowablePublish.java:429)
	at io.reactivex.e.e.b.cg$c.onComplete(FlowablePublish.java:252)
	at io.reactivex.e.e.b.dm$a.onComplete(FlowableSubscribeOn.java:108)
	at io.reactivex.e.e.b.aa$a.c(FlowableCreate.java:262)
	at io.reactivex.e.e.b.aa$a.n_(FlowableCreate.java:254)
	at eu.darken.rxshell.shell.RxShell.lambda$makeLineStream$6$RxShell(RxShell.java:190)
	at eu.darken.rxshell.shell.RxShell$$Lambda$6.subscribe(Unknown Source:4)
	at io.reactivex.e.e.b.aa.subscribeActual(FlowableCreate.java:72)
	at io.reactivex.i.subscribe(Flowable.java:13041)
	at io.reactivex.i.subscribe(Flowable.java:12987)
	at io.reactivex.e.e.b.dm$a.run(FlowableSubscribeOn.java:82)
	at io.reactivex.e.g.l.run(ScheduledRunnable.java:61)
	at io.reactivex.e.g.l.call(ScheduledRunnable.java:52)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.io.IOException: Upstream completed prematurely.
	... 23 more
```

**Comment by d4rken** [comment]
From  `Observable.zip(...)`

> The operator subscribes to its sources in order they are specified and completes eagerly if one of the sources is shorter than the rest while disposing the other sources. Therefore, it is possible those other sources will never be able to run to completion (and thus not calling doOnComplete()). **This can also happen if the sources are exactly the same length**; if source A completes and B has been consumed and is about to complete, the operator detects A won't be sending further values and it will dispose B immediately.

I think `zip` disposes one of the `Harvester`s prematurely before `onErrorReturnItem` can get us completely out of the `OnErrorNotImplementedException` situation.

**Comment by d4rken** [comment]
In hindsight I think this change wasn't actually the solution.

```
io.reactivex.exceptions.OnErrorNotImplementedException: Upstream completed prematurely.
	at io.reactivex.e.b.a$af.accept(Functions.java:1704)
	at io.reactivex.e.h.k.onError(LambdaSubscriber.java:79)
	at io.reactivex.i.b.onError(PublishProcessor.java:2325) <----------
	at eu.darken.rxshell.cmd.Harvester$BaseSub.onError(Harvester.java:96)
```

This wasn't a bug in the library but in a supplied  `Processor` that didn't have an error listener.

No harm done though, the current code is still better than previously.
